name: 'gcr.io/cloud-builders/gcloud'
on:
  push:
    branches:
      - main
  steps:
    - name: gcr.io/cloud-builders/gcloud'
      run: |
        cd app/angular
        npm install -g @angular/cli@9.1
        npm install
        npm run build-dev
  steps: 
    - name: 'gcr.io/cloud-builders/gcloud'
      uses: actions-hub/gcloud@master
      env:
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEV }}
        PROJECT_ID: ${{ secrets.PROJECT_ID_DEV }}
      with:
        args: "app deploy app/app.yaml --project=${{ secrets.PROJECT_ID_DEV }}"